stages:
    - "deploy"

deploy:android:
    stage: deploy
    before_script:
        - echo "PATH='${PATH}'"
        - export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v14.11.0/bin"
        - npm install
    script:
        - cd android && ./gradlew assembleRelease
        - cp android/app/build/outputs/apk/app-release.apk $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.apk
    artifacts:
        name: "$CI_PROJECT_NAME-$PLATFORM-$CI_COMMIT_REF_NAME"
        paths:
            - $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.apk
        expire_in: 7 days
